iwolfisberg/rent-a-cat

db/seeds.rb
J'ai modifié la seed pour créer 5 chats au lieu de 2, avec chacun une photo.
=> Seed completed

app/assets/stylesheets/components/_banner_show.scss, app/assets/stylesheets/components/_card_cat_show.scss, app/assets/stylesheets/pages/_show.scss, app/views/cats/show.html.erb
Voilà, j'ai fait la mise en page (basique pour le moment), ça ressemble à ça:
=> Mise en forme fini

app/assets/stylesheets/components/_card_cat_index.scss, app/views/cats/index.html.erb
Les cartes sont posées avec un lien sur le nom du chat.
=> Html index

app/javascript/components/_navbar.js, app/javascript/packs/application.js, app/views/cats/show.html.erb, app/views/shared/_navbar.html.erb
=> Cat show display photo

app/controllers/cats_controller.rb
J'ai juste ajouté un order(created_at: :desc) à la méthode index pour classer les chats par ordre de creation (du plus récent au plus ancien)
=> order cat by creation date in index

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_card_cat_index.scss, app/assets/stylesheets/components/_navbar.scss, app/views/cats/index.html.erb, app/views/cats/new.html.erb, app/views/shared/_navbar.html.erb
J'ai modifié la navbar, voilà comment ca apparait quand on est pas loggué: 
et quand on est loggué:
Nico, j'ai du modifié le main container, alors j'ai changé 1-2 petites choses pour que ta view reste la même !
=> Modif navbar

app/assets/stylesheets/components/_form.scss, app/views/devise/confirmations/new.html.erb, app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/email_changed.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_error_messages.html.erb, app/views/devise/shared/_links.html.erb, app/views/devise/unlocks/new.html.erb
=> Formulaire connexion terminé

app/controllers/rentals_controller.rb
=> lien mon profil créé

app/assets/stylesheets/components/_card_cat_index.scss, app/views/cats/index.html.erb
J'ai fait le responsive pour l'index (minus la navbar)
en small device: 
en medium.device (type table):
et pour tous les devices plus grands (c'est la page habituelle):
=> Responsive index

db/seeds.rb
Pour une seed qui fasse plus "réelle" : 
- J'ai mis des photos différentes pour chaque chat
- J'ai mis une adresse différente par user
Ca marche chez moi en local... j'espère que ca marchera également sur Heroku !
=> Modification de la seed

app/assets/stylesheets/components/_card_cat_index.scss, app/assets/stylesheets/components/_navbar.scss
La navbar est aussi responsive (j'ai juste du modifier la taille des cartes pour que se soit ok, 80% au lieu de 80vh.
=> Modified width index card for small device so navbar is responsive

Gemfile.lock, app/controllers/application_controller.rb, app/controllers/cats_controller.rb, app/policies/application_policy.rb, app/views/cats/index.html.erb, app/views/cats/new.html.erb, app/views/cats/show.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/layouts/application.html.erb, app/views/pages/myprofile.html.erb, app/views/shared/_flashed.html.erb
Modifié les autorisations: on a accès sans login à l'index/home et show, mais pas au reste. De plus, dans le formulaire de sign up, j'ai ajouté le username en obligatoire (faudra surement modifier la seed)
=> Ajouter les autorisations (accès à index et show sans login)

Gemfile, Gemfile.lock, config/initializers/geocoder.rb, db/migrate/20190522120546_add_coordinates_to_cats.rb, db/schema.rb
Ajouté une gem et une migration pour geocde
Faire 
bundle install
yarn install
rails db:migrate
=> geocode configuration

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_card_cat_index.scss, app/views/cats/index.html.erb, app/views/pages/myprofile.html.erb, app/views/shared/_navbar.html.erb
J'ai enlevé "Home" de la navbar (redondant)
J'ai fait que toutes les cartes (sur index et sur myprofile) soit des liens et j'ai modifié le css
=> Modif navbar et lien index

app/assets/stylesheets/components/_card_cat_index.scss, app/assets/stylesheets/components/_form.scss, app/views/cats/index.html.erb, app/views/cats/new.html.erb
En plus, comme j'avais mis en lien les cartes, j'ai du revoir le responsive, mais c'est tout bon :)
=> Modifier mise en forme form new + régler problème card responsive

app/assets/stylesheets/components/_card_cat_index.scss, app/assets/stylesheets/components/_card_profile.scss, app/views/cats/new.html.erb, app/views/cats/show.html.erb, app/views/layouts/application.html.erb, app/views/pages/myprofile.html.erb
J'ai juste changé le label dans le formulaire d'ajouter d'un chat (avant c'était adresse, maintenant, c'est rue).
J'ai aussi modifié le layout du myprofile et en responsive:
=> Modifier layout myprofile (aussi responsive), et changer label rue dans form new cat

app/javascript/packs/application.js, app/javascript/plugins/flatpickr.js, app/views/layouts/application.html.erb, app/views/shared/_form_rental.html.erb, package.json, yarn.lock
J'ai ajouté flatpickr pour rendre plus joli notre calendrier. Il vous faudra donc faire "yarn add flatpickr"
Pour votre info, voilà le tuto du wagon que j'ai suivi: https://kitt.lewagon.com/knowledge/tutorials/flatpickr, et aussi pour les options: https://flatpickr.js.org/options/
=> Flat pickr

app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/components/_card_cat_index.scss, app/assets/stylesheets/components/_card_cat_show.scss, app/controllers/cats_controller.rb, app/views/cats/index.html.erb, app/views/cats/show.html.erb, app/views/pages/myprofile.html.erb
J'ai ajouté l'avatar du owner sur les cartes du chat dans l'index et aussi sur la show. Je voulais tester de mettre un lien vers les profils de chacun, mais je ne sais pas encore comment le faire. Je mets dans les optionnels sur trello ;)
Ca ressemble à ça:
=> Avatar index

app/assets/javascripts/application.js, app/controllers/cats_controller.rb, app/controllers/rentals_controller.rb, app/javascript/packs/map.js, app/views/cats/index.html.erb, app/views/layouts/application.html.erb, config/initializers/geocoder.rb, package.json, yarn.lock
J'ai ajouté une map google avec les markers de nos chats dans l'index.  
Il y aurait des choses à ajouter comme des windows avec les infos par exemple.
=> Jt map google

app/views/shared/_navbar.html.erb, yarn.lock
J'ai rajouté l'avatar dans la navbar pour le dropdown.
=> WIP do not merge

app/controllers/reviews_controller.rb, app/views/cats/show.html.erb, app/views/pages/myprofile.html.erb, app/views/reviews/_show.html.erb
=> La show fonctionne

app/views/cats/index.html.erb, app/views/cats/show.html.erb, app/views/pages/myprofile.html.erb, app/views/reviews/new.html.erb
=> review finale

app/assets/stylesheets/components/_banner_show.scss, app/assets/stylesheets/components/_form_rental.scss, app/views/cats/show.html.erb
=> layout photo show
